/* Generated by Pyrex 0.9.5 on Wed May 18 01:59:47 2011 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "openssl/rand.h"
#include "stdlib.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ncrypt_rand */

static int __pyx_k3;
static PyObject *__pyx_k4;


/* Implementation of ncrypt_rand */


static PyObject *__pyx_n_ncrypt_err;
static PyObject *__pyx_n_RandError;
static PyObject *__pyx_n_bytes;
static PyObject *__pyx_n_pseudoBytes;
static PyObject *__pyx_n_seed;
static PyObject *__pyx_n_status;
static PyObject *__pyx_n_BaseLibraryError;

static PyObject *__pyx_n_ValueError;

static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;

static char (__pyx_k5[]) = "'num' should be > 0";
static char (__pyx_k6[]) = "RNG not seeded sufficiently";

static PyObject *__pyx_f_11ncrypt_rand_bytes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11ncrypt_rand_bytes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_num;
  int __pyx_v_checkResult;
  char (*__pyx_v_buf);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"num","checkResult",0};
  __pyx_v_checkResult = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i|i", __pyx_argnames, &__pyx_v_num, &__pyx_v_checkResult)) return 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":24 */
  __pyx_1 = (__pyx_v_num <= 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":25 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k5p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":26 */
  __pyx_v_buf = ((char (*))malloc(__pyx_v_num));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":27 */
  /*try:*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":28 */
    __pyx_v_result = RAND_bytes(((unsigned char (*))__pyx_v_buf),__pyx_v_num);

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":29 */
    __pyx_1 = __pyx_v_checkResult;
    if (__pyx_1) {
      __pyx_1 = (__pyx_v_result == 0);
    }
    if (__pyx_1) {

      /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":30 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_RandError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L4;}
      __Pyx_Raise(__pyx_2, __pyx_k6p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L4;}
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":31 */
    __pyx_2 = PyString_FromStringAndSize(__pyx_v_buf,__pyx_v_num); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L4;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L3;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L5;
    __pyx_L3: __pyx_why = 3; goto __pyx_L5;
    __pyx_L4: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":33 */
    free(__pyx_v_buf);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_rand.bytes");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_k7p;

static char (__pyx_k7[]) = "'num' should be > 0";

static PyObject *__pyx_f_11ncrypt_rand_pseudoBytes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11ncrypt_rand_pseudoBytes(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_num;
  char (*__pyx_v_buf);
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"num",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_num)) return 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":37 */
  __pyx_1 = (__pyx_v_num <= 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":38 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k7p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":39 */
  __pyx_v_buf = ((char (*))malloc(__pyx_v_num));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":40 */
  /*try:*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":41 */
    RAND_pseudo_bytes(((unsigned char (*))__pyx_v_buf),__pyx_v_num);

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":42 */
    __pyx_2 = PyString_FromStringAndSize(__pyx_v_buf,__pyx_v_num); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L4;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L3;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L5;
    __pyx_L3: __pyx_why = 3; goto __pyx_L5;
    __pyx_L4: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":44 */
    free(__pyx_v_buf);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_rand.pseudoBytes");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k8p;

static char (__pyx_k8[]) = "a string is expected";

static PyObject *__pyx_f_11ncrypt_rand_seed(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11ncrypt_rand_seed(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  PyObject *__pyx_v_entropy = 0;
  char (*__pyx_v_ptr);
  int __pyx_v_size;
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  double __pyx_3;
  static char *__pyx_argnames[] = {"data","entropy",0};
  __pyx_v_entropy = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_data, &__pyx_v_entropy)) return 0;
  Py_INCREF(__pyx_v_data);
  Py_INCREF(__pyx_v_entropy);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":49 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_data,(&__pyx_v_ptr),(&__pyx_v_size));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":50 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":51 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k8p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":52 */
  __pyx_1 = __pyx_v_entropy == Py_None;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":53 */
    RAND_seed(__pyx_v_ptr,__pyx_v_size);
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":55 */
    __pyx_3 = PyFloat_AsDouble(__pyx_v_entropy); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    RAND_add(__pyx_v_ptr,__pyx_v_size,__pyx_3);
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_rand.seed");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_data);
  Py_DECREF(__pyx_v_entropy);
  return __pyx_r;
}

static PyObject *__pyx_f_11ncrypt_rand_status(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11ncrypt_rand_status(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":58 */
  __pyx_1 = PyInt_FromLong(RAND_status()); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_rand.status");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_BaseLibraryError, "BaseLibraryError"},
  {&__pyx_n_RandError, "RandError"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n_ValueError, "ValueError"},
  {&__pyx_n_bytes, "bytes"},
  {&__pyx_n_ncrypt_err, "ncrypt_err"},
  {&__pyx_n_pseudoBytes, "pseudoBytes"},
  {&__pyx_n_seed, "seed"},
  {&__pyx_n_status, "status"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"bytes", (PyCFunction)__pyx_f_11ncrypt_rand_bytes, METH_VARARGS|METH_KEYWORDS, 0},
  {"pseudoBytes", (PyCFunction)__pyx_f_11ncrypt_rand_pseudoBytes, METH_VARARGS|METH_KEYWORDS, 0},
  {"seed", (PyCFunction)__pyx_f_11ncrypt_rand_seed, METH_VARARGS|METH_KEYWORDS, 0},
  {"status", (PyCFunction)__pyx_f_11ncrypt_rand_status, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initncrypt_rand(void); /*proto*/
PyMODINIT_FUNC initncrypt_rand(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("ncrypt_rand", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":17 */
  __pyx_1 = __Pyx_Import(__pyx_n_ncrypt_err, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ncrypt_err, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":19 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_ncrypt_err); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_BaseLibraryError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_RandError, "ncrypt_rand"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_RandError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":21 */
  __pyx_k3 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":46 */
  Py_INCREF(Py_None);
  __pyx_k4 = Py_None;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_rand.pyx":57 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_rand");
}

static char *__pyx_filenames[] = {
  "ncrypt_rand.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
