/* Generated by Pyrex 0.9.5 on Wed May 18 01:59:46 2011 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "openssl/evp.h"
#include "utils.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ncrypt_cipher */


struct __pyx_obj_13ncrypt_cipher_CipherType {
  PyObject_HEAD
  EVP_CIPHER (*c);
  PyObject *cipherAlgo;
  PyObject *cipherMode;
};


struct __pyx_obj_13ncrypt_cipher_Cipher {
  PyObject_HEAD
  struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *__pyx_vtab;
  char (*outBuffer);
  int outBufferSize;
  EVP_CIPHER_CTX (*ctx);
  int cipherFinalized;
};

struct __pyx_vtabstruct_13ncrypt_cipher_Cipher {
  void ((*growBuffer)(struct __pyx_obj_13ncrypt_cipher_Cipher *,int ));
  PyObject *((*_finish)(struct __pyx_obj_13ncrypt_cipher_Cipher *));
};
static struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *__pyx_vtabptr_13ncrypt_cipher_Cipher;

static PyTypeObject *__pyx_ptype_13ncrypt_cipher_CipherType = 0;
static PyTypeObject *__pyx_ptype_13ncrypt_cipher_Cipher = 0;
static PyObject *__pyx_k13;


/* Implementation of ncrypt_cipher */

static char (__pyx_k8[]) = "DES-EDE3";
static char (__pyx_k10[]) = "AES-128";
static char (__pyx_k11[]) = "AES-192";
static char (__pyx_k12[]) = "AES-256";

static PyObject *__pyx_n_ncrypt_err;
static PyObject *__pyx_n_CipherError;
static PyObject *__pyx_n_MODES;
static PyObject *__pyx_n_ALGORITHMS;
static PyObject *__pyx_n_EncryptCipher;
static PyObject *__pyx_n_DecryptCipher;
static PyObject *__pyx_n_BaseLibraryError;
static PyObject *__pyx_n_CBC;
static PyObject *__pyx_n_CFB;
static PyObject *__pyx_n_OFB;
static PyObject *__pyx_n_ECB;
static PyObject *__pyx_n_DES;
static PyObject *__pyx_n_BF;

static PyObject *__pyx_k8p;
static PyObject *__pyx_k10p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;

static int __pyx_f_13ncrypt_cipher_10CipherType___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_cipher_10CipherType___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cipherAlgo = 0;
  PyObject *__pyx_v_cipherMode = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"cipherAlgo","cipherMode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_cipherAlgo, &__pyx_v_cipherMode)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_cipherAlgo);
  Py_INCREF(__pyx_v_cipherMode);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":47 */
  ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c = 0;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_cipherAlgo);
  Py_DECREF(__pyx_v_cipherMode);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_cipher_10CipherType___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13ncrypt_cipher_10CipherType___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":50 */

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_join;

static PyObject *__pyx_k14p;
static PyObject *__pyx_k15p;

static char (__pyx_k14[]) = "-";
static char (__pyx_k15[]) = "unknown cipher: %s";

static int __pyx_f_13ncrypt_cipher_10CipherType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_cipher_10CipherType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cipherAlgo = 0;
  PyObject *__pyx_v_cipherMode = 0;
  PyObject *__pyx_v_cipherName;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  char (*__pyx_4);
  int __pyx_5;
  static char *__pyx_argnames[] = {"cipherAlgo","cipherMode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_cipherAlgo, &__pyx_v_cipherMode)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_cipherAlgo);
  Py_INCREF(__pyx_v_cipherMode);
  __pyx_v_cipherName = Py_None; Py_INCREF(Py_None);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":53 */
  __pyx_1 = PyObject_GetAttr(__pyx_k14p, __pyx_n_join); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  __pyx_2 = PyList_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  Py_INCREF(__pyx_v_cipherAlgo);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_v_cipherAlgo);
  Py_INCREF(__pyx_v_cipherMode);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_v_cipherMode);
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_cipherName);
  __pyx_v_cipherName = __pyx_2;
  __pyx_2 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":54 */
  Py_INCREF(__pyx_v_cipherAlgo);
  Py_DECREF(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherAlgo);
  ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherAlgo = __pyx_v_cipherAlgo;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":55 */
  Py_INCREF(__pyx_v_cipherMode);
  Py_DECREF(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherMode);
  ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherMode = __pyx_v_cipherMode;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":56 */
  __pyx_4 = PyString_AsString(__pyx_v_cipherName); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c = ((EVP_CIPHER (*))EVP_get_cipherbyname(__pyx_4));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":57 */
  __pyx_5 = (((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c == 0);
  if (__pyx_5) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":58 */
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k15p, __pyx_v_cipherName); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __Pyx_Raise(__pyx_1, __pyx_3, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_cipher.CipherType.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cipherName);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_cipherAlgo);
  Py_DECREF(__pyx_v_cipherMode);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_algo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_algo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherAlgo);
  __pyx_r = ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherAlgo;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_mode(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_mode(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherMode);
  __pyx_r = ((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->cipherMode;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_name(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_name(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":64 */
  __pyx_1 = PyString_FromString(EVP_CIPHER_name(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_cipher.CipherType.name");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_blockSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_blockSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":67 */
  __pyx_1 = PyInt_FromLong(EVP_CIPHER_block_size(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_cipher.CipherType.blockSize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_keyLength(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_keyLength(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":70 */
  __pyx_1 = PyInt_FromLong(EVP_CIPHER_key_length(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_cipher.CipherType.keyLength");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_ivLength(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_10CipherType_ivLength(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":73 */
  __pyx_1 = PyInt_FromLong(EVP_CIPHER_iv_length(((struct __pyx_obj_13ncrypt_cipher_CipherType *)__pyx_v_self)->c)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_cipher.CipherType.ivLength");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_EncryptCipher(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_EncryptCipher(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cipherType = 0;
  PyObject *__pyx_v_key = 0;
  PyObject *__pyx_v_iv = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"cipherType","key","iv",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_cipherType, &__pyx_v_key, &__pyx_v_iv)) return 0;
  Py_INCREF(__pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  Py_INCREF(__pyx_v_iv);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":76 */
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_INCREF(__pyx_v_cipherType);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_key);
  Py_INCREF(__pyx_v_iv);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_v_iv);
  PyTuple_SET_ITEM(__pyx_2, 3, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_13ncrypt_cipher_Cipher), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_cipher.EncryptCipher");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cipherType);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_iv);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_DecryptCipher(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_DecryptCipher(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cipherType = 0;
  PyObject *__pyx_v_key = 0;
  PyObject *__pyx_v_iv = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"cipherType","key","iv",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_cipherType, &__pyx_v_key, &__pyx_v_iv)) return 0;
  Py_INCREF(__pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  Py_INCREF(__pyx_v_iv);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":79 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  Py_INCREF(__pyx_v_cipherType);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_key);
  Py_INCREF(__pyx_v_iv);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_v_iv);
  PyTuple_SET_ITEM(__pyx_2, 3, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_13ncrypt_cipher_Cipher), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_cipher.DecryptCipher");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_cipherType);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_iv);
  return __pyx_r;
}

static int __pyx_f_13ncrypt_cipher_6Cipher___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_cipher_6Cipher___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cipherType = 0;
  PyObject *__pyx_v_key = 0;
  PyObject *__pyx_v_iv = 0;
  PyObject *__pyx_v_encryptFlag = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"cipherType","key","iv","encryptFlag",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_cipherType, &__pyx_v_key, &__pyx_v_iv, &__pyx_v_encryptFlag)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  Py_INCREF(__pyx_v_iv);
  Py_INCREF(__pyx_v_encryptFlag);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":88 */
  ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBuffer = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":89 */
  ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBufferSize = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":90 */
  ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx = AllocCipherContext();

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":91 */
  EVP_CIPHER_CTX_init(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":92 */
  ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->cipherFinalized = 0;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_cipherType);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_iv);
  Py_DECREF(__pyx_v_encryptFlag);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_cipher_6Cipher___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13ncrypt_cipher_6Cipher___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":95 */
  EVP_CIPHER_CTX_cleanup(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":96 */
  FreeCipherContext(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":97 */
  free(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBuffer);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_TypeError;
static PyObject *__pyx_n_keyLength;
static PyObject *__pyx_n_ivLength;

static PyObject *__pyx_k16p;
static PyObject *__pyx_k17p;
static PyObject *__pyx_k18p;
static PyObject *__pyx_k19p;
static PyObject *__pyx_k20p;

static char (__pyx_k16[]) = "'key' must be a string";
static char (__pyx_k17[]) = "invalid key length %d, expected %d";
static char (__pyx_k18[]) = "'iv' must be a string";
static char (__pyx_k19[]) = "invalid iv length %d, expected %d";
static char (__pyx_k20[]) = "unable to initialize cipher";

static int __pyx_f_13ncrypt_cipher_6Cipher___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_cipher_6Cipher___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_13ncrypt_cipher_CipherType *__pyx_v_cipherType = 0;
  PyObject *__pyx_v_key = 0;
  PyObject *__pyx_v_iv = 0;
  PyObject *__pyx_v_encryptFlag = 0;
  char (*__pyx_v_keyPtr);
  char (*__pyx_v_ivPtr);
  int __pyx_v_keyLen;
  int __pyx_v_ivLen;
  int __pyx_v_result;
  int __pyx_v_enc;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"cipherType","key","iv","encryptFlag",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_cipherType, &__pyx_v_key, &__pyx_v_iv, &__pyx_v_encryptFlag)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_cipherType);
  Py_INCREF(__pyx_v_key);
  Py_INCREF(__pyx_v_iv);
  Py_INCREF(__pyx_v_encryptFlag);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_cipherType), __pyx_ptype_13ncrypt_cipher_CipherType, 0, "cipherType")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":102 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_key,(&__pyx_v_keyPtr),(&__pyx_v_keyLen));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":103 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":104 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k16p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":105 */
  __pyx_2 = PyInt_FromLong(__pyx_v_keyLen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_cipherType), __pyx_n_keyLength); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_Cmp(__pyx_2, __pyx_4, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_1 = __pyx_1 != 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":106 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(__pyx_v_keyLen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(((PyObject *)__pyx_v_cipherType), __pyx_n_keyLength); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_4, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
    __pyx_2 = 0;
    __pyx_5 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k17p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_3, __pyx_2, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":107 */
  __pyx_1 = __pyx_v_iv == Py_None;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":108 */
    __pyx_v_ivPtr = 0;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":109 */
    __pyx_v_ivLen = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":111 */
    __pyx_v_result = PyString_AsStringAndSize(__pyx_v_iv,(&__pyx_v_ivPtr),(&__pyx_v_ivLen));

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":112 */
    __pyx_1 = (__pyx_v_result < 0);
    if (__pyx_1) {

      /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":113 */
      __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
      __Pyx_Raise(__pyx_5, __pyx_k18p, 0);
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":114 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ivLen); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_cipherType), __pyx_n_ivLength); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    __pyx_2 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (PyObject_Cmp(__pyx_4, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
    __pyx_1 = __pyx_1 != 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_1) {

      /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":115 */
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(__pyx_v_ivLen); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      __pyx_4 = PyObject_GetAttr(((PyObject *)__pyx_v_cipherType), __pyx_n_ivLength); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      __pyx_2 = PyObject_CallObject(__pyx_4, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
      PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
      __pyx_3 = 0;
      __pyx_2 = 0;
      __pyx_3 = PyNumber_Remainder(__pyx_k19p, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __Pyx_Raise(__pyx_5, __pyx_3, 0);
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L4:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":117 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_encryptFlag); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_v_enc = 1;
    goto __pyx_L7;
  }
  /*else*/ {
    __pyx_v_enc = 0;
  }
  __pyx_L7:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":119 */
  __pyx_v_result = EVP_CipherInit_ex(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx,__pyx_v_cipherType->c,0,((unsigned char (*))__pyx_v_keyPtr),((unsigned char (*))__pyx_v_ivPtr),__pyx_v_enc);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":121 */
  __pyx_1 = (__pyx_v_result == 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":122 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k20p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    goto __pyx_L8;
  }
  __pyx_L8:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":123 */
  ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->cipherFinalized = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("ncrypt_cipher.Cipher.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_cipherType);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_iv);
  Py_DECREF(__pyx_v_encryptFlag);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_enablePadding(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_enablePadding(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_padding = 0;
  int __pyx_v_paddingFlag;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"padding",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_padding)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_padding);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":127 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_padding); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_v_paddingFlag = 1;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_v_paddingFlag = 0;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":129 */
  EVP_CIPHER_CTX_set_padding(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx,__pyx_v_paddingFlag);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("ncrypt_cipher.Cipher.enablePadding");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_padding);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_cipher_6Cipher_growBuffer(struct __pyx_obj_13ncrypt_cipher_Cipher *__pyx_v_self,int __pyx_v_requiredSize) {
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":132 */
  __pyx_1 = (__pyx_v_requiredSize > __pyx_v_self->outBufferSize);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":133 */
    __pyx_v_self->outBuffer = ((char (*))realloc(__pyx_v_self->outBuffer,__pyx_v_requiredSize));

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":134 */
    __pyx_v_self->outBufferSize = __pyx_v_requiredSize;
    goto __pyx_L2;
  }
  __pyx_L2:;

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_k21p;
static PyObject *__pyx_k22p;
static PyObject *__pyx_k23p;
static PyObject *__pyx_k24p;

static char (__pyx_k21[]) = "cipher operation already completed";
static char (__pyx_k22[]) = "a string is required";
static char (__pyx_k23[]) = "";
static char (__pyx_k24[]) = "error in cipher operation";

static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_update(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_update(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  char (*__pyx_v_inData);
  int __pyx_v_inDataLen;
  int __pyx_v_outDataLen;
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"data",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":139 */
  __pyx_1 = ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->cipherFinalized;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":140 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k21p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":141 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_data,(&__pyx_v_inData),(&__pyx_v_inDataLen));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":142 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":143 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k22p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":144 */
  __pyx_1 = (__pyx_v_inDataLen == 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":145 */
    Py_INCREF(__pyx_k23p);
    __pyx_r = __pyx_k23p;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":146 */
  ((struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *)((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->__pyx_vtab)->growBuffer(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self),(__pyx_v_inDataLen + EVP_MAX_BLOCK_LENGTH));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":147 */
  __pyx_v_outDataLen = ((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBufferSize;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":148 */
  __pyx_v_result = EVP_CipherUpdate(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->ctx,((unsigned char (*))((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBuffer),(&__pyx_v_outDataLen),((unsigned char (*))__pyx_v_inData),__pyx_v_inDataLen);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":150 */
  __pyx_1 = (__pyx_v_result == 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":151 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k24p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":152 */
  __pyx_2 = PyString_FromStringAndSize(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->outBuffer,__pyx_v_outDataLen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_cipher.Cipher.update");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static PyObject *__pyx_k25p;
static PyObject *__pyx_k26p;

static char (__pyx_k25[]) = "cipher operation already completed";
static char (__pyx_k26[]) = "error in cipher operation";

static PyObject *__pyx_f_13ncrypt_cipher_6Cipher__finish(struct __pyx_obj_13ncrypt_cipher_Cipher *__pyx_v_self) {
  int __pyx_v_outDataLen;
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":155 */
  __pyx_1 = __pyx_v_self->cipherFinalized;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":156 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k25p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":157 */
  __pyx_v_self->cipherFinalized = 1;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":159 */
  ((struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *)__pyx_v_self->__pyx_vtab)->growBuffer(__pyx_v_self,EVP_MAX_BLOCK_LENGTH);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":160 */
  __pyx_v_outDataLen = __pyx_v_self->outBufferSize;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":161 */
  __pyx_v_result = EVP_CipherFinal_ex(__pyx_v_self->ctx,((unsigned char (*))__pyx_v_self->outBuffer),(&__pyx_v_outDataLen));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":163 */
  __pyx_1 = (__pyx_v_result == 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":164 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_CipherError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k26p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":165 */
  __pyx_2 = PyString_FromStringAndSize(__pyx_v_self->outBuffer,__pyx_v_outDataLen); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_cipher.Cipher._finish");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_update;

static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_finish(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_cipher_6Cipher_finish(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"data",0};
  __pyx_v_data = __pyx_k13;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":168 */
  __pyx_1 = __pyx_v_data != Py_None;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":169 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_update); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_INCREF(__pyx_v_data);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_data);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = ((struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *)((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->__pyx_vtab)->_finish(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_3 = PyNumber_Add(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":171 */
    __pyx_4 = ((struct __pyx_vtabstruct_13ncrypt_cipher_Cipher *)((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)->__pyx_vtab)->_finish(((struct __pyx_obj_13ncrypt_cipher_Cipher *)__pyx_v_self)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
    __pyx_r = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_cipher.Cipher.finish");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_ALGORITHMS, "ALGORITHMS"},
  {&__pyx_n_BF, "BF"},
  {&__pyx_n_BaseLibraryError, "BaseLibraryError"},
  {&__pyx_n_CBC, "CBC"},
  {&__pyx_n_CFB, "CFB"},
  {&__pyx_n_CipherError, "CipherError"},
  {&__pyx_n_DES, "DES"},
  {&__pyx_n_DecryptCipher, "DecryptCipher"},
  {&__pyx_n_ECB, "ECB"},
  {&__pyx_n_EncryptCipher, "EncryptCipher"},
  {&__pyx_n_MODES, "MODES"},
  {&__pyx_n_OFB, "OFB"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n_ivLength, "ivLength"},
  {&__pyx_n_join, "join"},
  {&__pyx_n_keyLength, "keyLength"},
  {&__pyx_n_ncrypt_err, "ncrypt_err"},
  {&__pyx_n_update, "update"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k16p, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k17p, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_k18p, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k19p, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_k20p, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k21p, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_k22p, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k23p, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_k24p, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k25p, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_k26p, __pyx_k26, sizeof(__pyx_k26)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_13ncrypt_cipher_CipherType(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13ncrypt_cipher_CipherType *p = (struct __pyx_obj_13ncrypt_cipher_CipherType *)o;
  p->cipherAlgo = Py_None; Py_INCREF(Py_None);
  p->cipherMode = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_13ncrypt_cipher_10CipherType___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13ncrypt_cipher_CipherType(PyObject *o) {
  struct __pyx_obj_13ncrypt_cipher_CipherType *p = (struct __pyx_obj_13ncrypt_cipher_CipherType *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13ncrypt_cipher_10CipherType___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->cipherAlgo);
  Py_XDECREF(p->cipherMode);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13ncrypt_cipher_CipherType(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13ncrypt_cipher_CipherType *p = (struct __pyx_obj_13ncrypt_cipher_CipherType *)o;
  if (p->cipherAlgo) {
    e = (*v)(p->cipherAlgo, a); if (e) return e;
  }
  if (p->cipherMode) {
    e = (*v)(p->cipherMode, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_13ncrypt_cipher_CipherType(PyObject *o) {
  struct __pyx_obj_13ncrypt_cipher_CipherType *p = (struct __pyx_obj_13ncrypt_cipher_CipherType *)o;
  Py_XDECREF(p->cipherAlgo);
  p->cipherAlgo = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->cipherMode);
  p->cipherMode = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_13ncrypt_cipher_CipherType[] = {
  {"algo", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_algo, METH_VARARGS|METH_KEYWORDS, 0},
  {"mode", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_mode, METH_VARARGS|METH_KEYWORDS, 0},
  {"name", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_name, METH_VARARGS|METH_KEYWORDS, 0},
  {"blockSize", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_blockSize, METH_VARARGS|METH_KEYWORDS, 0},
  {"keyLength", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_keyLength, METH_VARARGS|METH_KEYWORDS, 0},
  {"ivLength", (PyCFunction)__pyx_f_13ncrypt_cipher_10CipherType_ivLength, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_CipherType = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_CipherType = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_CipherType = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_CipherType = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13ncrypt_cipher_CipherType = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_cipher.CipherType", /*tp_name*/
  sizeof(struct __pyx_obj_13ncrypt_cipher_CipherType), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13ncrypt_cipher_CipherType, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_CipherType, /*tp_as_number*/
  &__pyx_tp_as_sequence_CipherType, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_CipherType, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_CipherType, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13ncrypt_cipher_CipherType, /*tp_traverse*/
  __pyx_tp_clear_13ncrypt_cipher_CipherType, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13ncrypt_cipher_CipherType, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13ncrypt_cipher_10CipherType___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13ncrypt_cipher_CipherType, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_13ncrypt_cipher_Cipher __pyx_vtable_13ncrypt_cipher_Cipher;

static PyObject *__pyx_tp_new_13ncrypt_cipher_Cipher(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13ncrypt_cipher_Cipher *p = (struct __pyx_obj_13ncrypt_cipher_Cipher *)o;
  *(struct __pyx_vtabstruct_13ncrypt_cipher_Cipher **)&p->__pyx_vtab = __pyx_vtabptr_13ncrypt_cipher_Cipher;
  if (__pyx_f_13ncrypt_cipher_6Cipher___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13ncrypt_cipher_Cipher(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13ncrypt_cipher_6Cipher___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13ncrypt_cipher_Cipher(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_13ncrypt_cipher_Cipher(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_13ncrypt_cipher_Cipher[] = {
  {"enablePadding", (PyCFunction)__pyx_f_13ncrypt_cipher_6Cipher_enablePadding, METH_VARARGS|METH_KEYWORDS, 0},
  {"update", (PyCFunction)__pyx_f_13ncrypt_cipher_6Cipher_update, METH_VARARGS|METH_KEYWORDS, 0},
  {"finish", (PyCFunction)__pyx_f_13ncrypt_cipher_6Cipher_finish, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Cipher = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Cipher = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Cipher = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Cipher = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13ncrypt_cipher_Cipher = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_cipher.Cipher", /*tp_name*/
  sizeof(struct __pyx_obj_13ncrypt_cipher_Cipher), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13ncrypt_cipher_Cipher, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Cipher, /*tp_as_number*/
  &__pyx_tp_as_sequence_Cipher, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Cipher, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Cipher, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13ncrypt_cipher_Cipher, /*tp_traverse*/
  __pyx_tp_clear_13ncrypt_cipher_Cipher, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13ncrypt_cipher_Cipher, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13ncrypt_cipher_6Cipher___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13ncrypt_cipher_Cipher, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"EncryptCipher", (PyCFunction)__pyx_f_13ncrypt_cipher_EncryptCipher, METH_VARARGS|METH_KEYWORDS, 0},
  {"DecryptCipher", (PyCFunction)__pyx_f_13ncrypt_cipher_DecryptCipher, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initncrypt_cipher(void); /*proto*/
PyMODINIT_FUNC initncrypt_cipher(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("ncrypt_cipher", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_type_13ncrypt_cipher_CipherType.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_13ncrypt_cipher_CipherType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "CipherType", (PyObject *)&__pyx_type_13ncrypt_cipher_CipherType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_ptype_13ncrypt_cipher_CipherType = &__pyx_type_13ncrypt_cipher_CipherType;
  __pyx_vtabptr_13ncrypt_cipher_Cipher = &__pyx_vtable_13ncrypt_cipher_Cipher;
  *(void(**)())&__pyx_vtable_13ncrypt_cipher_Cipher.growBuffer = (void(*)())__pyx_f_13ncrypt_cipher_6Cipher_growBuffer;
  *(void(**)())&__pyx_vtable_13ncrypt_cipher_Cipher._finish = (void(*)())__pyx_f_13ncrypt_cipher_6Cipher__finish;
  if (PyType_Ready(&__pyx_type_13ncrypt_cipher_Cipher) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13ncrypt_cipher_Cipher.tp_dict, __pyx_vtabptr_13ncrypt_cipher_Cipher) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Cipher", (PyObject *)&__pyx_type_13ncrypt_cipher_Cipher) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_ptype_13ncrypt_cipher_Cipher = &__pyx_type_13ncrypt_cipher_Cipher;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":35 */
  __pyx_1 = __Pyx_Import(__pyx_n_ncrypt_err, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ncrypt_err, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":37 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_ncrypt_err); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_BaseLibraryError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_CipherError, "ncrypt_cipher"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_CipherError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":39 */
  __pyx_2 = PyTuple_New(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  Py_INCREF(__pyx_n_CBC);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_CBC);
  Py_INCREF(__pyx_n_CFB);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_n_CFB);
  Py_INCREF(__pyx_n_OFB);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_n_OFB);
  Py_INCREF(__pyx_n_ECB);
  PyTuple_SET_ITEM(__pyx_2, 3, __pyx_n_ECB);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MODES, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":40 */
  __pyx_3 = PyTuple_New(6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_INCREF(__pyx_n_DES);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_DES);
  Py_INCREF(__pyx_k8p);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_k8p);
  Py_INCREF(__pyx_n_BF);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_n_BF);
  Py_INCREF(__pyx_k10p);
  PyTuple_SET_ITEM(__pyx_3, 3, __pyx_k10p);
  Py_INCREF(__pyx_k11p);
  PyTuple_SET_ITEM(__pyx_3, 4, __pyx_k11p);
  Py_INCREF(__pyx_k12p);
  PyTuple_SET_ITEM(__pyx_3, 5, __pyx_k12p);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ALGORITHMS, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_cipher.pyx":167 */
  Py_INCREF(Py_None);
  __pyx_k13 = Py_None;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_cipher");
}

static char *__pyx_filenames[] = {
  "ncrypt_cipher.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
