/* Generated by Pyrex 0.9.5 on Wed May 18 01:59:46 2011 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "openssl/evp.h"
#include "utils.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ncrypt_digest */


struct __pyx_obj_13ncrypt_digest_DigestType {
  PyObject_HEAD
  EVP_MD (*m);
};


struct __pyx_obj_13ncrypt_digest_Digest {
  PyObject_HEAD
  struct __pyx_vtabstruct_13ncrypt_digest_Digest *__pyx_vtab;
  EVP_MD_CTX (*ctx);
  int digestFinalized;
  PyObject *digestType;
};

struct __pyx_vtabstruct_13ncrypt_digest_Digest {
  void ((*cleanupCtx)(struct __pyx_obj_13ncrypt_digest_Digest *));
};
static struct __pyx_vtabstruct_13ncrypt_digest_Digest *__pyx_vtabptr_13ncrypt_digest_Digest;

static PyTypeObject *__pyx_ptype_13ncrypt_digest_DigestType = 0;
static PyTypeObject *__pyx_ptype_13ncrypt_digest_Digest = 0;
static PyObject *__pyx_k9;


/* Implementation of ncrypt_digest */


static PyObject *__pyx_n_ncrypt_err;
static PyObject *__pyx_n_DigestError;
static PyObject *__pyx_n_ALGORITHMS;
static PyObject *__pyx_n_BaseLibraryError;
static PyObject *__pyx_n_MD5;
static PyObject *__pyx_n_SHA1;
static PyObject *__pyx_n_SHA224;
static PyObject *__pyx_n_SHA256;
static PyObject *__pyx_n_SHA384;
static PyObject *__pyx_n_SHA512;

static int __pyx_f_13ncrypt_digest_10DigestType___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_digest_10DigestType___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_evpMd = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"evpMd",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_evpMd)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_evpMd);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":36 */
  ((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m = 0;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_evpMd);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_digest_10DigestType___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13ncrypt_digest_10DigestType___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":39 */

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_k10p;

static char (__pyx_k10[]) = "unknown digest: %s";

static int __pyx_f_13ncrypt_digest_10DigestType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_digest_10DigestType___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_evpMd = 0;
  int __pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"evpMd",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_evpMd)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_evpMd);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":42 */
  __pyx_1 = PyString_AsString(__pyx_v_evpMd); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  ((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m = ((EVP_MD (*))EVP_get_digestbyname(__pyx_1));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":43 */
  __pyx_2 = (((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m == 0);
  if (__pyx_2) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":44 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __pyx_4 = PyNumber_Remainder(__pyx_k10p, __pyx_v_evpMd); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __Pyx_Raise(__pyx_3, __pyx_4, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_digest.DigestType.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_evpMd);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_digest_10DigestType_name(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_10DigestType_name(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":47 */
  __pyx_1 = PyString_FromString(EVP_MD_name(((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_digest.DigestType.name");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_digest_10DigestType_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_10DigestType_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":50 */
  __pyx_1 = PyInt_FromLong(EVP_MD_size(((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_digest.DigestType.size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_digest_10DigestType_blockSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_10DigestType_blockSize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":53 */
  __pyx_1 = PyInt_FromLong(EVP_MD_block_size(((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_digest.DigestType.blockSize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_digest_10DigestType_nid(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_10DigestType_nid(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":56 */
  __pyx_1 = PyInt_FromLong(EVP_MD_type(((struct __pyx_obj_13ncrypt_digest_DigestType *)__pyx_v_self)->m)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_digest.DigestType.nid");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_13ncrypt_digest_6Digest___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_digest_6Digest___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_digestType = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"digestType",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_digestType)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_digestType);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":64 */
  ((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->ctx = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":65 */
  ((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestFinalized = 0;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_digestType);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_digest_6Digest_cleanupCtx(struct __pyx_obj_13ncrypt_digest_Digest *__pyx_v_self) {
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":68 */
  __pyx_1 = (__pyx_v_self->ctx != 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":69 */
    EVP_MD_CTX_destroy(__pyx_v_self->ctx);

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":70 */
    __pyx_v_self->ctx = 0;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":71 */
    __pyx_v_self->digestFinalized = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  Py_DECREF(__pyx_v_self);
}

static void __pyx_f_13ncrypt_digest_6Digest___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13ncrypt_digest_6Digest___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":74 */
  ((struct __pyx_vtabstruct_13ncrypt_digest_Digest *)((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->__pyx_vtab)->cleanupCtx(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self));

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_k11p;

static char (__pyx_k11[]) = "unable to initialize digest";

static int __pyx_f_13ncrypt_digest_6Digest___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_digest_6Digest___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_13ncrypt_digest_DigestType *__pyx_v_digestType = 0;
  int __pyx_v_result;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"digestType",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_digestType)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_digestType);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_digestType), __pyx_ptype_13ncrypt_digest_DigestType, 0, "digestType")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":77 */
  ((struct __pyx_vtabstruct_13ncrypt_digest_Digest *)((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->__pyx_vtab)->cleanupCtx(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":78 */
  ((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->ctx = EVP_MD_CTX_create();

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":80 */
  __pyx_v_result = EVP_DigestInit_ex(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->ctx,__pyx_v_digestType->m,0);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":81 */
  __pyx_1 = (__pyx_v_result != 1);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":82 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k11p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":83 */
  Py_INCREF(((PyObject *)__pyx_v_digestType));
  Py_DECREF(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestType);
  ((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestType = ((PyObject *)__pyx_v_digestType);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_digest.Digest.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_digestType);
  return __pyx_r;
}

static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;

static char (__pyx_k12[]) = "no further update() operations allowed";
static char (__pyx_k13[]) = "a string is expected";
static char (__pyx_k14[]) = "unable to update digest";

static PyObject *__pyx_f_13ncrypt_digest_6Digest_update(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_6Digest_update(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  char (*__pyx_v_s);
  int __pyx_v_slen;
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"data",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":86 */
  __pyx_1 = (((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestFinalized != 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":87 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k12p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":91 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_data,(&__pyx_v_s),(&__pyx_v_slen));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":92 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":93 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k13p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":94 */
  __pyx_v_result = EVP_DigestUpdate(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->ctx,__pyx_v_s,__pyx_v_slen);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":95 */
  __pyx_1 = (__pyx_v_result != 1);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":96 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k14p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_digest.Digest.update");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static PyObject *__pyx_n_update;

static PyObject *__pyx_k15p;
static PyObject *__pyx_k16p;

static char (__pyx_k15[]) = "digest operation is already completed";
static char (__pyx_k16[]) = "unable to finalize digest";

static PyObject *__pyx_f_13ncrypt_digest_6Digest_digest(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_digest_6Digest_digest(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  unsigned char (__pyx_v_md[EVP_MAX_MD_SIZE]);
  unsigned int __pyx_v_mdLen;
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"data",0};
  __pyx_v_data = __pyx_k9;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":99 */
  __pyx_1 = (((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestFinalized != 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":100 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k15p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":101 */
  __pyx_1 = __pyx_v_data != Py_None;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":102 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_update); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_INCREF(__pyx_v_data);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_data);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":106 */
  __pyx_v_result = EVP_DigestFinal_ex(((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->ctx,__pyx_v_md,(&__pyx_v_mdLen));

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":107 */
  __pyx_1 = (__pyx_v_result != 1);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":108 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DigestError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k16p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":109 */
  ((struct __pyx_obj_13ncrypt_digest_Digest *)__pyx_v_self)->digestFinalized = 1;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":110 */
  __pyx_3 = PyString_FromStringAndSize(((char (*))__pyx_v_md),((int )__pyx_v_mdLen)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_digest.Digest.digest");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_ALGORITHMS, "ALGORITHMS"},
  {&__pyx_n_BaseLibraryError, "BaseLibraryError"},
  {&__pyx_n_DigestError, "DigestError"},
  {&__pyx_n_MD5, "MD5"},
  {&__pyx_n_SHA1, "SHA1"},
  {&__pyx_n_SHA224, "SHA224"},
  {&__pyx_n_SHA256, "SHA256"},
  {&__pyx_n_SHA384, "SHA384"},
  {&__pyx_n_SHA512, "SHA512"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n_ncrypt_err, "ncrypt_err"},
  {&__pyx_n_update, "update"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k16p, __pyx_k16, sizeof(__pyx_k16)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_13ncrypt_digest_DigestType(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (__pyx_f_13ncrypt_digest_10DigestType___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13ncrypt_digest_DigestType(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13ncrypt_digest_10DigestType___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13ncrypt_digest_DigestType(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_13ncrypt_digest_DigestType(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_13ncrypt_digest_DigestType[] = {
  {"name", (PyCFunction)__pyx_f_13ncrypt_digest_10DigestType_name, METH_VARARGS|METH_KEYWORDS, 0},
  {"size", (PyCFunction)__pyx_f_13ncrypt_digest_10DigestType_size, METH_VARARGS|METH_KEYWORDS, 0},
  {"blockSize", (PyCFunction)__pyx_f_13ncrypt_digest_10DigestType_blockSize, METH_VARARGS|METH_KEYWORDS, 0},
  {"nid", (PyCFunction)__pyx_f_13ncrypt_digest_10DigestType_nid, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_DigestType = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_DigestType = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_DigestType = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_DigestType = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13ncrypt_digest_DigestType = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_digest.DigestType", /*tp_name*/
  sizeof(struct __pyx_obj_13ncrypt_digest_DigestType), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13ncrypt_digest_DigestType, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_DigestType, /*tp_as_number*/
  &__pyx_tp_as_sequence_DigestType, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_DigestType, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_DigestType, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13ncrypt_digest_DigestType, /*tp_traverse*/
  __pyx_tp_clear_13ncrypt_digest_DigestType, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13ncrypt_digest_DigestType, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13ncrypt_digest_10DigestType___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13ncrypt_digest_DigestType, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_13ncrypt_digest_Digest __pyx_vtable_13ncrypt_digest_Digest;

static PyObject *__pyx_tp_new_13ncrypt_digest_Digest(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13ncrypt_digest_Digest *p = (struct __pyx_obj_13ncrypt_digest_Digest *)o;
  *(struct __pyx_vtabstruct_13ncrypt_digest_Digest **)&p->__pyx_vtab = __pyx_vtabptr_13ncrypt_digest_Digest;
  p->digestType = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_13ncrypt_digest_6Digest___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13ncrypt_digest_Digest(PyObject *o) {
  struct __pyx_obj_13ncrypt_digest_Digest *p = (struct __pyx_obj_13ncrypt_digest_Digest *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13ncrypt_digest_6Digest___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->digestType);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13ncrypt_digest_Digest(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13ncrypt_digest_Digest *p = (struct __pyx_obj_13ncrypt_digest_Digest *)o;
  if (p->digestType) {
    e = (*v)(p->digestType, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_13ncrypt_digest_Digest(PyObject *o) {
  struct __pyx_obj_13ncrypt_digest_Digest *p = (struct __pyx_obj_13ncrypt_digest_Digest *)o;
  Py_XDECREF(p->digestType);
  p->digestType = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_13ncrypt_digest_Digest[] = {
  {"update", (PyCFunction)__pyx_f_13ncrypt_digest_6Digest_update, METH_VARARGS|METH_KEYWORDS, 0},
  {"digest", (PyCFunction)__pyx_f_13ncrypt_digest_6Digest_digest, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_13ncrypt_digest_Digest[] = {
  {"digestType", T_OBJECT, offsetof(struct __pyx_obj_13ncrypt_digest_Digest, digestType), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Digest = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Digest = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Digest = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Digest = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13ncrypt_digest_Digest = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_digest.Digest", /*tp_name*/
  sizeof(struct __pyx_obj_13ncrypt_digest_Digest), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13ncrypt_digest_Digest, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Digest, /*tp_as_number*/
  &__pyx_tp_as_sequence_Digest, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Digest, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Digest, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13ncrypt_digest_Digest, /*tp_traverse*/
  __pyx_tp_clear_13ncrypt_digest_Digest, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13ncrypt_digest_Digest, /*tp_methods*/
  __pyx_members_13ncrypt_digest_Digest, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13ncrypt_digest_6Digest___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13ncrypt_digest_Digest, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initncrypt_digest(void); /*proto*/
PyMODINIT_FUNC initncrypt_digest(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("ncrypt_digest", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_13ncrypt_digest_DigestType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "DigestType", (PyObject *)&__pyx_type_13ncrypt_digest_DigestType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  __pyx_ptype_13ncrypt_digest_DigestType = &__pyx_type_13ncrypt_digest_DigestType;
  __pyx_vtabptr_13ncrypt_digest_Digest = &__pyx_vtable_13ncrypt_digest_Digest;
  *(void(**)())&__pyx_vtable_13ncrypt_digest_Digest.cleanupCtx = (void(*)())__pyx_f_13ncrypt_digest_6Digest_cleanupCtx;
  __pyx_type_13ncrypt_digest_Digest.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_13ncrypt_digest_Digest) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13ncrypt_digest_Digest.tp_dict, __pyx_vtabptr_13ncrypt_digest_Digest) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Digest", (PyObject *)&__pyx_type_13ncrypt_digest_Digest) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_ptype_13ncrypt_digest_Digest = &__pyx_type_13ncrypt_digest_Digest;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":28 */
  __pyx_1 = __Pyx_Import(__pyx_n_ncrypt_err, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ncrypt_err, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":30 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_ncrypt_err); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_BaseLibraryError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_DigestError, "ncrypt_digest"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_DigestError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":32 */
  __pyx_2 = PyTuple_New(6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_INCREF(__pyx_n_MD5);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_MD5);
  Py_INCREF(__pyx_n_SHA1);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_n_SHA1);
  Py_INCREF(__pyx_n_SHA224);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_n_SHA224);
  Py_INCREF(__pyx_n_SHA256);
  PyTuple_SET_ITEM(__pyx_2, 3, __pyx_n_SHA256);
  Py_INCREF(__pyx_n_SHA384);
  PyTuple_SET_ITEM(__pyx_2, 4, __pyx_n_SHA384);
  Py_INCREF(__pyx_n_SHA512);
  PyTuple_SET_ITEM(__pyx_2, 5, __pyx_n_SHA512);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ALGORITHMS, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_digest.pyx":98 */
  Py_INCREF(Py_None);
  __pyx_k9 = Py_None;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_digest");
}

static char *__pyx_filenames[] = {
  "ncrypt_digest.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
