/* Generated by Pyrex 0.9.5 on Sat May 21 07:00:51 2011 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "openssl/dh.h"
#include "openssl/bn.h"
#include "openssl/bio.h"
#include "openssl/pem.h"
#include "utils.h"
#include "stdlib.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ncrypt_dh */


struct __pyx_obj_9ncrypt_dh_DH {
  PyObject_HEAD
  DH (*dh);
};

static PyTypeObject *__pyx_ptype_9ncrypt_dh_DH = 0;


/* Implementation of ncrypt_dh */


static PyObject *__pyx_n_ncrypt_err;
static PyObject *__pyx_n_DHError;
static PyObject *__pyx_n_BaseLibraryError;

static int __pyx_f_9ncrypt_dh_2DH___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9ncrypt_dh_2DH___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":54 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh = DH_new();

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_9ncrypt_dh_2DH___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_9ncrypt_dh_2DH___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":57 */
  DH_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

  Py_DECREF(__pyx_v_self);
}

static int __pyx_f_9ncrypt_dh_2DH___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9ncrypt_dh_2DH___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":60 */

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k3p;

static char (__pyx_k3[]) = "dh params not initialized";

static PyObject *__pyx_f_9ncrypt_dh_2DH_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":63 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":64 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k3p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":65 */
  __pyx_2 = PyInt_FromLong(DH_size(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "error generating dh parameters";

static PyObject *__pyx_f_9ncrypt_dh_2DH_generateParameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_generateParameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_primeLen = 0;
  PyObject *__pyx_v_generator = 0;
  DH (*__pyx_v_newdh);
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"primeLen","generator",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_primeLen, &__pyx_v_generator)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_primeLen);
  Py_INCREF(__pyx_v_generator);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":69 */
  __pyx_1 = PyInt_AsLong(__pyx_v_primeLen); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_generator); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_v_newdh = DH_generate_parameters(__pyx_1,__pyx_2,0,0);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":71 */
  __pyx_1 = (!(__pyx_v_newdh != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":72 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    __Pyx_Raise(__pyx_3, __pyx_k4p, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":73 */
  DH_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":74 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh = __pyx_v_newdh;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_dh.DH.generateParameters");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_primeLen);
  Py_DECREF(__pyx_v_generator);
  return __pyx_r;
}

static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;

static char (__pyx_k5[]) = "dh params not initialized";
static char (__pyx_k6[]) = "error in check dh params";
static char (__pyx_k7[]) = "dh params are not ok (%d)";

static PyObject *__pyx_f_9ncrypt_dh_2DH_check(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_check(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_result;
  int __pyx_v_codes;
  PyObject *__pyx_v_msg;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_msg = Py_None; Py_INCREF(Py_None);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":77 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":78 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k5p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":80 */
  __pyx_v_result = DH_check(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh,(&__pyx_v_codes));

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":81 */
  __pyx_1 = (!__pyx_v_result);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":82 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k6p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":83 */
  __pyx_1 = __pyx_v_codes;
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":84 */
    __pyx_2 = PyInt_FromLong(__pyx_v_codes); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k7p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_msg);
    __pyx_v_msg = __pyx_3;
    __pyx_3 = 0;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":85 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_v_msg, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_dh.DH.check");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_msg);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;

static char (__pyx_k8[]) = "dh params are not initialized";
static char (__pyx_k9[]) = "error in generating key";

static PyObject *__pyx_f_9ncrypt_dh_2DH_generateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_generateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":88 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":89 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k8p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":91 */
  __pyx_v_result = DH_generate_key(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":92 */
  __pyx_1 = (!__pyx_v_result);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":93 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k9p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.generateKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k10p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;

static char (__pyx_k10[]) = "dh params are not initialized";
static char (__pyx_k11[]) = "dh private key not initialized";
static char (__pyx_k12[]) = "invalid peerPubKey value";
static char (__pyx_k13[]) = "error in computing shared key";

static PyObject *__pyx_f_9ncrypt_dh_2DH_computeKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_computeKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_peerPubKey = 0;
  BIGNUM (*__pyx_v_bn_peerPubKey);
  int __pyx_v_result;
  unsigned char (*__pyx_v_keyBuf);
  PyObject *__pyx_v_sharedKey;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"peerPubKey",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_peerPubKey)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_peerPubKey);
  __pyx_v_sharedKey = Py_None; Py_INCREF(Py_None);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":96 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":97 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k10p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":98 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":99 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k11p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":102 */
  __pyx_v_bn_peerPubKey = BN_new();

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":103 */
  __pyx_v_result = LongToBN(__pyx_v_peerPubKey,__pyx_v_bn_peerPubKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":104 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":105 */
    BN_free(__pyx_v_bn_peerPubKey);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":106 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k12p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":108 */
  __pyx_v_keyBuf = ((unsigned char (*))malloc(DH_size(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh)));

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":109 */
  __pyx_v_result = DH_compute_key(__pyx_v_keyBuf,__pyx_v_bn_peerPubKey,((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":110 */
  BN_free(__pyx_v_bn_peerPubKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":111 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":112 */
    free(__pyx_v_keyBuf);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":113 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k13p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":114 */
  __pyx_2 = PyString_FromStringAndSize(((char (*))__pyx_v_keyBuf),__pyx_v_result); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_v_sharedKey);
  __pyx_v_sharedKey = __pyx_2;
  __pyx_2 = 0;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":115 */
  free(__pyx_v_keyBuf);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":116 */
  Py_INCREF(__pyx_v_sharedKey);
  __pyx_r = __pyx_v_sharedKey;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.computeKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_sharedKey);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_peerPubKey);
  return __pyx_r;
}

static PyObject *__pyx_f_9ncrypt_dh_2DH_getP(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_getP(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":119 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":120 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":121 */
  __pyx_2 = BNToLong(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.getP");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k14p;

static char (__pyx_k14[]) = "invalid p value";

static PyObject *__pyx_f_9ncrypt_dh_2DH_setP(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_setP(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_p = 0;
  BIGNUM (*__pyx_v_bn_p);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"p",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_p)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_p);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":126 */
  __pyx_v_bn_p = BN_new();

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":127 */
  __pyx_v_result = LongToBN(__pyx_v_p,__pyx_v_bn_p);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":128 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":129 */
    BN_free(__pyx_v_bn_p);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":130 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k14p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":131 */
  __pyx_1 = (((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":132 */
    BN_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":133 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p = __pyx_v_bn_p;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.setP");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_p);
  return __pyx_r;
}

static PyObject *__pyx_f_9ncrypt_dh_2DH_getG(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_getG(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":136 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":137 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":138 */
  __pyx_2 = BNToLong(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.getG");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k15p;

static char (__pyx_k15[]) = "invalid g value";

static PyObject *__pyx_f_9ncrypt_dh_2DH_setG(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_setG(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_g = 0;
  BIGNUM (*__pyx_v_bn_g);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"g",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_g)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_g);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":143 */
  __pyx_v_bn_g = BN_new();

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":144 */
  __pyx_v_result = LongToBN(__pyx_v_g,__pyx_v_bn_g);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":145 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":146 */
    BN_free(__pyx_v_bn_g);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":147 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k15p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":148 */
  __pyx_1 = (((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":149 */
    BN_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":150 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g = __pyx_v_bn_g;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.setG");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_g);
  return __pyx_r;
}

static PyObject *__pyx_f_9ncrypt_dh_2DH_getPublicKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_getPublicKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":153 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":154 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":155 */
  __pyx_2 = BNToLong(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.getPublicKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k16p;

static char (__pyx_k16[]) = "invalid pubKey value";

static PyObject *__pyx_f_9ncrypt_dh_2DH_setPublicKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_setPublicKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pubKey = 0;
  BIGNUM (*__pyx_v_bn_pubKey);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"pubKey",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_pubKey)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pubKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":160 */
  __pyx_v_bn_pubKey = BN_new();

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":161 */
  __pyx_v_result = LongToBN(__pyx_v_pubKey,__pyx_v_bn_pubKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":162 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":163 */
    BN_free(__pyx_v_bn_pubKey);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":164 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k16p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":165 */
  __pyx_1 = (((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key != 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":166 */
    BN_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":167 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->pub_key = __pyx_v_bn_pubKey;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.setPublicKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pubKey);
  return __pyx_r;
}

static PyObject *__pyx_f_9ncrypt_dh_2DH_getPrivateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_getPrivateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":170 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":171 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":172 */
  __pyx_2 = BNToLong(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.getPrivateKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k17p;

static char (__pyx_k17[]) = "invalid privKey value";

static PyObject *__pyx_f_9ncrypt_dh_2DH_setPrivateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_setPrivateKey(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_privKey = 0;
  BIGNUM (*__pyx_v_bn_privKey);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"privKey",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_privKey)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_privKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":177 */
  __pyx_v_bn_privKey = BN_new();

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":178 */
  __pyx_v_result = LongToBN(__pyx_v_privKey,__pyx_v_bn_privKey);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":179 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":180 */
    BN_free(__pyx_v_bn_privKey);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":181 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k17p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":182 */
  __pyx_1 = (((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key != 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":183 */
    BN_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":184 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->priv_key = __pyx_v_bn_privKey;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.setPrivateKey");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_privKey);
  return __pyx_r;
}

static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k18p;
static PyObject *__pyx_k19p;

static char (__pyx_k18[]) = "a string is expected";
static char (__pyx_k19[]) = "unable to load object from data";

static PyObject *__pyx_f_9ncrypt_dh_2DH_fromDER_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_fromDER_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  char (*__pyx_v_p);
  int __pyx_v_result;
  int __pyx_v_dataLen;
  DH (*__pyx_v_newdh);
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"data",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":189 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_data,(&__pyx_v_p),(&__pyx_v_dataLen));

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":190 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":191 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k18p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":193 */
  __pyx_v_newdh = d2i_DHparams(0,((unsigned char (*(*)))(&__pyx_v_p)),__pyx_v_dataLen);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":194 */
  __pyx_1 = (!(__pyx_v_newdh != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":195 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k19p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":196 */
  DH_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":197 */
  ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh = __pyx_v_newdh;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_dh.DH.fromDER_Parameters");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static PyObject *__pyx_n_MemoryError;

static PyObject *__pyx_k20p;
static PyObject *__pyx_k21p;
static PyObject *__pyx_k22p;

static char (__pyx_k20[]) = "dh params not initialized";
static char (__pyx_k21[]) = "error in dh params data";
static char (__pyx_k22[]) = "unable to allocate string";

static PyObject *__pyx_f_9ncrypt_dh_2DH_toDER_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_toDER_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_len;
  PyObject (*__pyx_v_derStr);
  char (*__pyx_v_p);
  PyObject *__pyx_v_len1;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_len1 = Py_None; Py_INCREF(Py_None);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":200 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":201 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k20p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":203 */
  __pyx_v_len = i2d_DHparams(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh,0);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":204 */
  __pyx_1 = (__pyx_v_len < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":205 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k21p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":207 */
  __pyx_v_derStr = PyString_FromStringAndSize(0,__pyx_v_len);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":208 */
  __pyx_1 = (__pyx_v_derStr == 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":209 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_MemoryError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k22p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":211 */
  __pyx_v_p = PyString_AsString(__pyx_v_derStr);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":212 */
  /*try:*/ {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":213 */
    __pyx_2 = PyInt_FromLong(i2d_DHparams(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh,((unsigned char (*(*)))(&__pyx_v_p)))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L6;}
    Py_DECREF(__pyx_v_len1);
    __pyx_v_len1 = __pyx_2;
    __pyx_2 = 0;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":214 */
    __pyx_2 = PyInt_FromLong(__pyx_v_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L6;}
    if (PyObject_Cmp(__pyx_2, __pyx_v_len1, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L6;}
    __pyx_1 = __pyx_1 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_1) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L6;}
    }

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":215 */
    __pyx_2 = (PyObject *)__pyx_v_derStr;
    Py_INCREF(__pyx_2);
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L5;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L7;
    __pyx_L5: __pyx_why = 3; goto __pyx_L7;
    __pyx_L6: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":217 */
    Py_DECREF(__pyx_v_derStr);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_dh.DH.toDER_Parameters");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_len1);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k23p;
static PyObject *__pyx_k24p;
static PyObject *__pyx_k25p;
static PyObject *__pyx_k26p;

static char (__pyx_k23[]) = "a string is expected";
static char (__pyx_k24[]) = "unable to allocate BIO structure";
static char (__pyx_k25[]) = "unable to write data to BIO";
static char (__pyx_k26[]) = "unable to load object from data";

static PyObject *__pyx_f_9ncrypt_dh_2DH_fromPEM_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_fromPEM_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  char (*__pyx_v_p);
  int __pyx_v_dataLen;
  int __pyx_v_result;
  BIO (*__pyx_v_b);
  DH (*__pyx_v_newdh);
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"data",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":222 */
  __pyx_v_result = PyString_AsStringAndSize(__pyx_v_data,(&__pyx_v_p),(&__pyx_v_dataLen));

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":223 */
  __pyx_1 = (__pyx_v_result < 0);
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":224 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k23p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":226 */
  __pyx_v_b = BIO_new(BIO_s_mem());

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":227 */
  __pyx_1 = (!(__pyx_v_b != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":228 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k24p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":230 */
  /*try:*/ {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":231 */
    __pyx_v_result = BIO_write(__pyx_v_b,__pyx_v_p,__pyx_v_dataLen);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":232 */
    __pyx_1 = (__pyx_v_result < 0);
    if (__pyx_1) {

      /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":233 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L5;}
      __Pyx_Raise(__pyx_2, __pyx_k25p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L5;}
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":234 */
    __pyx_v_newdh = PEM_read_bio_DHparams(__pyx_v_b,0,0,0);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":235 */
    __pyx_1 = (!(__pyx_v_newdh != 0));
    if (__pyx_1) {

      /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":236 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L5;}
      __Pyx_Raise(__pyx_2, __pyx_k26p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L5;}
      goto __pyx_L8;
    }
    __pyx_L8:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":237 */
    DH_free(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":238 */
    ((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh = __pyx_v_newdh;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L6;
    __pyx_L5: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":240 */
    BIO_free(__pyx_v_b);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_dh.DH.fromPEM_Parameters");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static PyObject *__pyx_k27p;
static PyObject *__pyx_k28p;
static PyObject *__pyx_k29p;
static PyObject *__pyx_k30p;

static char (__pyx_k27[]) = "dh params not initialized";
static char (__pyx_k28[]) = "unable to allocate a BIO structure";
static char (__pyx_k29[]) = "error in dh params data";
static char (__pyx_k30[]) = "error in creating PEM data";

static PyObject *__pyx_f_9ncrypt_dh_2DH_toPEM_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9ncrypt_dh_2DH_toPEM_Parameters(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  BIO (*__pyx_v_b);
  int __pyx_v_result;
  PyObject *__pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_ret = Py_None; Py_INCREF(Py_None);

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":243 */
  __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->p != 0));
  if (!__pyx_1) {
    __pyx_1 = (!(((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh->g != 0));
  }
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":244 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k27p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":246 */
  __pyx_v_b = BIO_new(BIO_s_mem());

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":247 */
  __pyx_1 = (!(__pyx_v_b != 0));
  if (__pyx_1) {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":248 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 248; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k28p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 248; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":250 */
  /*try:*/ {

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":251 */
    __pyx_v_result = PEM_write_bio_DHparams(__pyx_v_b,((struct __pyx_obj_9ncrypt_dh_DH *)__pyx_v_self)->dh);

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":252 */
    __pyx_1 = (!__pyx_v_result);
    if (__pyx_1) {

      /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":253 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L5;}
      __Pyx_Raise(__pyx_2, __pyx_k29p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L5;}
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":254 */
    __pyx_2 = GetBIOData(__pyx_v_b); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L5;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_2;
    __pyx_2 = 0;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":255 */
    __pyx_1 = __pyx_v_ret == Py_None;
    if (__pyx_1) {

      /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":256 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_DHError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 256; goto __pyx_L5;}
      __Pyx_Raise(__pyx_2, __pyx_k30p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 256; goto __pyx_L5;}
      goto __pyx_L8;
    }
    __pyx_L8:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":257 */
    Py_INCREF(__pyx_v_ret);
    __pyx_r = __pyx_v_ret;
    goto __pyx_L4;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L6;
    __pyx_L4: __pyx_why = 3; goto __pyx_L6;
    __pyx_L5: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_2); __pyx_2 = 0;
      PyErr_Fetch(&__pyx_2, &__pyx_3, &__pyx_4);
      __pyx_1 = __pyx_lineno;
      goto __pyx_L6;
    }
    __pyx_L6:;

    /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":259 */
    BIO_free(__pyx_v_b);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_2, __pyx_3, __pyx_4);
        __pyx_lineno = __pyx_1;
        __pyx_2 = 0;
        __pyx_3 = 0;
        __pyx_4 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("ncrypt_dh.DH.toPEM_Parameters");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ret);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_BaseLibraryError, "BaseLibraryError"},
  {&__pyx_n_DHError, "DHError"},
  {&__pyx_n_MemoryError, "MemoryError"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n_ncrypt_err, "ncrypt_err"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k16p, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k17p, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_k18p, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k19p, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_k20p, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k21p, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_k22p, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k23p, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_k24p, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k25p, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_k26p, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_k27p, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_k28p, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_k29p, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_k30p, __pyx_k30, sizeof(__pyx_k30)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_9ncrypt_dh_DH(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (__pyx_f_9ncrypt_dh_2DH___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_9ncrypt_dh_DH(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_9ncrypt_dh_2DH___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9ncrypt_dh_DH(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_9ncrypt_dh_DH(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_9ncrypt_dh_DH[] = {
  {"size", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_size, METH_VARARGS|METH_KEYWORDS, 0},
  {"generateParameters", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_generateParameters, METH_VARARGS|METH_KEYWORDS, 0},
  {"check", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_check, METH_VARARGS|METH_KEYWORDS, 0},
  {"generateKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_generateKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"computeKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_computeKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"getP", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_getP, METH_VARARGS|METH_KEYWORDS, 0},
  {"setP", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_setP, METH_VARARGS|METH_KEYWORDS, 0},
  {"getG", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_getG, METH_VARARGS|METH_KEYWORDS, 0},
  {"setG", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_setG, METH_VARARGS|METH_KEYWORDS, 0},
  {"getPublicKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_getPublicKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"setPublicKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_setPublicKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"getPrivateKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_getPrivateKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"setPrivateKey", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_setPrivateKey, METH_VARARGS|METH_KEYWORDS, 0},
  {"fromDER_Parameters", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_fromDER_Parameters, METH_VARARGS|METH_KEYWORDS, 0},
  {"toDER_Parameters", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_toDER_Parameters, METH_VARARGS|METH_KEYWORDS, 0},
  {"fromPEM_Parameters", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_fromPEM_Parameters, METH_VARARGS|METH_KEYWORDS, 0},
  {"toPEM_Parameters", (PyCFunction)__pyx_f_9ncrypt_dh_2DH_toPEM_Parameters, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_DH = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_DH = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_DH = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_DH = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9ncrypt_dh_DH = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_dh.DH", /*tp_name*/
  sizeof(struct __pyx_obj_9ncrypt_dh_DH), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9ncrypt_dh_DH, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_DH, /*tp_as_number*/
  &__pyx_tp_as_sequence_DH, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_DH, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_DH, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9ncrypt_dh_DH, /*tp_traverse*/
  __pyx_tp_clear_9ncrypt_dh_DH, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9ncrypt_dh_DH, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_9ncrypt_dh_2DH___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9ncrypt_dh_DH, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initncrypt_dh(void); /*proto*/
PyMODINIT_FUNC initncrypt_dh(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("ncrypt_dh", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_9ncrypt_dh_DH) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "DH", (PyObject *)&__pyx_type_9ncrypt_dh_DH) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  __pyx_ptype_9ncrypt_dh_DH = &__pyx_type_9ncrypt_dh_DH;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":48 */
  __pyx_1 = __Pyx_Import(__pyx_n_ncrypt_err, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ncrypt_err, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":50 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_ncrypt_err); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_BaseLibraryError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_DHError, "ncrypt_dh"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_DHError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/ivan/Super-Adventure-Club/ncrypt-0.6.4/ncrypt_dh.pyx":242 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_dh");
}

static char *__pyx_filenames[] = {
  "ncrypt_dh.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
