/* Generated by Pyrex 0.9.5 on Wed May 18 01:59:46 2011 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "openssl/bn.h"
#include "openssl/crypto.h"
#include "stdlib.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from ncrypt_bignum */


struct __pyx_obj_13ncrypt_bignum_BigNum {
  PyObject_HEAD
  struct __pyx_vtabstruct_13ncrypt_bignum_BigNum *__pyx_vtab;
  BIGNUM (*bn);
};

struct __pyx_vtabstruct_13ncrypt_bignum_BigNum {
  PyObject *((*_free)(struct __pyx_obj_13ncrypt_bignum_BigNum *));
};
static struct __pyx_vtabstruct_13ncrypt_bignum_BigNum *__pyx_vtabptr_13ncrypt_bignum_BigNum;

static PyTypeObject *__pyx_ptype_13ncrypt_bignum_BigNum = 0;
static PyObject *__pyx_k1;
static PyObject *__pyx_k2;


/* Implementation of ncrypt_bignum */

static int __pyx_f_13ncrypt_bignum_6BigNum___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_bignum_6BigNum___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"x",0};
  __pyx_v_x = __pyx_k1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_x)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":33 */
  ((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn = BN_new();

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum__free(struct __pyx_obj_13ncrypt_bignum_BigNum *__pyx_v_self) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":36 */
  BN_free(__pyx_v_self->bn);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":37 */
  __pyx_v_self->bn = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_13ncrypt_bignum_6BigNum___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_13ncrypt_bignum_6BigNum___dealloc__(PyObject *__pyx_v_self) {
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":40 */
  __pyx_1 = ((struct __pyx_vtabstruct_13ncrypt_bignum_BigNum *)((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->__pyx_vtab)->_free(((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_ValueError;
static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;

static char (__pyx_k3[]) = "invalid string value passed";
static char (__pyx_k4[]) = "invalid type passed, require int/long/str";

static int __pyx_f_13ncrypt_bignum_6BigNum___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13ncrypt_bignum_6BigNum___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  char (*__pyx_v_s);
  int __pyx_v_result;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  __pyx_v_x = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_x)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":43 */
  __pyx_1 = PyInt_Check(__pyx_v_x);
  if (!__pyx_1) {
    __pyx_1 = PyLong_Check(__pyx_v_x);
  }
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":44 */
    __pyx_2 = PyObject_Str(__pyx_v_x); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_v_x);
    __pyx_v_x = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":47 */
  __pyx_1 = PyString_Check(__pyx_v_x);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":48 */
    __pyx_v_s = PyString_AsString(__pyx_v_x);

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":49 */
    __pyx_v_result = BN_dec2bn((&((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn),__pyx_v_s);

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":50 */
    __pyx_1 = (__pyx_v_result == 0);
    if (__pyx_1) {

      /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":51 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
      __Pyx_Raise(__pyx_2, __pyx_k3p, 0);
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;
    goto __pyx_L3;
  }
  __pyx_1 = __pyx_v_x != Py_None;
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":53 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k4p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":56 */
  BN_clear(((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_toLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_toLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_s);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":60 */
  __pyx_v_s = BN_bn2dec(((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":61 */
  /*try:*/ {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":62 */
    __pyx_1 = PyLong_FromString(__pyx_v_s,0,10); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L3;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L2;
  }
  /*finally:*/ {
    int __pyx_why;
    __pyx_why = 0; goto __pyx_L4;
    __pyx_L2: __pyx_why = 3; goto __pyx_L4;
    __pyx_L3: {
      __pyx_why = 4;
      Py_XDECREF(__pyx_1); __pyx_1 = 0;
      PyErr_Fetch(&__pyx_1, &__pyx_2, &__pyx_3);
      __pyx_4 = __pyx_lineno;
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":64 */
    OPENSSL_free(__pyx_v_s);
    switch (__pyx_why) {
      case 3: goto __pyx_L0;
      case 4: {
        PyErr_Restore(__pyx_1, __pyx_2, __pyx_3);
        __pyx_lineno = __pyx_4;
        __pyx_1 = 0;
        __pyx_2 = 0;
        __pyx_3 = 0;
        goto __pyx_L1;
      }
    }
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.toLong");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;

static char (__pyx_k5[]) = "long/int type required";
static char (__pyx_k6[]) = "invalid string value passed";

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_fromLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_fromLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  char (*__pyx_v_s);
  int __pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":67 */
  __pyx_1 = (!PyLong_Check(__pyx_v_x));
  if (__pyx_1) {
    __pyx_1 = (!PyInt_Check(__pyx_v_x));
  }
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":68 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k5p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":69 */
  __pyx_2 = PyObject_Str(__pyx_v_x); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_v_x);
  __pyx_v_x = __pyx_2;
  __pyx_2 = 0;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":72 */
  __pyx_v_s = PyString_AsString(__pyx_v_x);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":73 */
  __pyx_v_result = BN_dec2bn((&((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn),__pyx_v_s);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":74 */
  __pyx_1 = (__pyx_v_result == 0);
  if (__pyx_1) {

    /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":75 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_ValueError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_k6p, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.fromLong");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_numBytes(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_numBytes(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":78 */
  __pyx_1 = PyInt_FromLong(BN_num_bytes(((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.numBytes");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_numBits(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13ncrypt_bignum_6BigNum_numBits(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":81 */
  __pyx_1 = PyInt_FromLong(BN_num_bits(((struct __pyx_obj_13ncrypt_bignum_BigNum *)__pyx_v_self)->bn)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("ncrypt_bignum.BigNum.numBits");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n_ValueError, "ValueError"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {0, 0, 0}
};
static struct __pyx_vtabstruct_13ncrypt_bignum_BigNum __pyx_vtable_13ncrypt_bignum_BigNum;

static PyObject *__pyx_tp_new_13ncrypt_bignum_BigNum(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13ncrypt_bignum_BigNum *p = (struct __pyx_obj_13ncrypt_bignum_BigNum *)o;
  *(struct __pyx_vtabstruct_13ncrypt_bignum_BigNum **)&p->__pyx_vtab = __pyx_vtabptr_13ncrypt_bignum_BigNum;
  if (__pyx_f_13ncrypt_bignum_6BigNum___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13ncrypt_bignum_BigNum(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13ncrypt_bignum_6BigNum___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13ncrypt_bignum_BigNum(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_13ncrypt_bignum_BigNum(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_13ncrypt_bignum_BigNum[] = {
  {"clear", (PyCFunction)__pyx_f_13ncrypt_bignum_6BigNum_clear, METH_VARARGS|METH_KEYWORDS, 0},
  {"toLong", (PyCFunction)__pyx_f_13ncrypt_bignum_6BigNum_toLong, METH_VARARGS|METH_KEYWORDS, 0},
  {"fromLong", (PyCFunction)__pyx_f_13ncrypt_bignum_6BigNum_fromLong, METH_VARARGS|METH_KEYWORDS, 0},
  {"numBytes", (PyCFunction)__pyx_f_13ncrypt_bignum_6BigNum_numBytes, METH_VARARGS|METH_KEYWORDS, 0},
  {"numBits", (PyCFunction)__pyx_f_13ncrypt_bignum_6BigNum_numBits, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BigNum = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BigNum = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BigNum = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BigNum = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13ncrypt_bignum_BigNum = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "ncrypt_bignum.BigNum", /*tp_name*/
  sizeof(struct __pyx_obj_13ncrypt_bignum_BigNum), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13ncrypt_bignum_BigNum, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BigNum, /*tp_as_number*/
  &__pyx_tp_as_sequence_BigNum, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BigNum, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BigNum, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13ncrypt_bignum_BigNum, /*tp_traverse*/
  __pyx_tp_clear_13ncrypt_bignum_BigNum, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13ncrypt_bignum_BigNum, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_13ncrypt_bignum_6BigNum___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13ncrypt_bignum_BigNum, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initncrypt_bignum(void); /*proto*/
PyMODINIT_FUNC initncrypt_bignum(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("ncrypt_bignum", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_vtabptr_13ncrypt_bignum_BigNum = &__pyx_vtable_13ncrypt_bignum_BigNum;
  *(void(**)())&__pyx_vtable_13ncrypt_bignum_BigNum._free = (void(*)())__pyx_f_13ncrypt_bignum_6BigNum__free;
  if (PyType_Ready(&__pyx_type_13ncrypt_bignum_BigNum) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_13ncrypt_bignum_BigNum.tp_dict, __pyx_vtabptr_13ncrypt_bignum_BigNum) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BigNum", (PyObject *)&__pyx_type_13ncrypt_bignum_BigNum) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_ptype_13ncrypt_bignum_BigNum = &__pyx_type_13ncrypt_bignum_BigNum;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":32 */
  Py_INCREF(Py_None);
  __pyx_k1 = Py_None;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":42 */
  Py_INCREF(Py_None);
  __pyx_k2 = Py_None;

  /* "/home/ivan/Desktop/ncrypt-0.6.4/ncrypt_bignum.pyx":80 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("ncrypt_bignum");
}

static char *__pyx_filenames[] = {
  "ncrypt_bignum.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
